    CREATE TABLE ecuator.t_ecuator_clients_initial (
        client_id INTEGER PRIMARY KEY,
        client_code VARCHAR(255),
        num_orders INTEGER,
        total_orders_value NUMERIC(10, 2),
        num_cancelled_orders INTEGER,
        total_cancelled_orders_value NUMERIC(10, 2),
        num_returned_orders INTEGER,
        total_returned_orders_value NUMERIC(10, 2),
        last_order_date DATE,
        client_group VARCHAR(255),
        client_name VARCHAR(255),
        client_company_name VARCHAR(255),
        email_address VARCHAR(255),
        phone_number VARCHAR(20),
        registration_date DATE,
        newsletter_subscription BOOLEAN,
        active_client BOOLEAN,
        client_tags TEXT,
        delivery_address TEXT,
        rfm_group VARCHAR(255),
        rfm_score NUMERIC,
        client_cards TEXT
    );